version: '3.8'

services:
  flask:
    build: .
    container_name: localtube
    ports:
      - "8080:8080"
    volumes:
    - /mnt/musicshare:/musicshare
    networks:
      - webnet

  caddy:
    image: caddy:latest
    container_name: caddy_server
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - flask
    networks:
      - webnet

networks:
  webnet:
